### ISSUE TITLE
FaQ / Guide / Wiki

### ISSUE THREAD

**Issue by ShinoMythmaker** [belzaru17/WorkshopOptimizerPlugin#1]
Hey ho, a simple guide or faq or just hover tooltips would be nice to know what is ment with all those tabs etc.

**Comment by belzaru17** [comment]
Hey! Thanks for the feedback! I'll try to get to it next weekend.

**Comment by belzaru17** [comment]
Added some basic usage in README.md.
Also simplified some of the usage and reordered tabs to front load the 2 more useful ones.
