### ISSUE TITLE
Dalamud API9 Update broke the plugin completly

### ISSUE THREAD

**Issue by Tatsu941** [belzaru17/WorkshopOptimizerPlugin#12]
Plugin needs a patch, is automatically disabled by Dalamud

**Comment by belzaru17** [comment]
Updated and pull request sent.

Thanks!

**Comment by dart9901** [comment]
How long does the pull become approved I see the update.  I went into dalamud in game and still shows old version as of 10-12-2023 just curious

**Comment by Tatsu941** [comment]
> How long does the pull become approved I see the update. I went into dalamud in game and still shows old version as of 10-12-2023 just curious

For me its up to date now. Also once the pull request is approved it still needs to be published under the new API9 as plugin update.

**Comment by belzaru17** [comment]
Pull request was approved ~6hs ago.  Let me know if you still don't see it ~tomorrow.

Thanks!

**Comment by dart9901** [comment]
Everything is up to date now thanks!  Love this plugin so much!

**Comment by belzaru17** [comment]
Happy to hear and thanks!
