### ISSUE TITLE
Plugin is generating agendas with items I have 0 of

### ISSUE THREAD

**Issue by ChrisZehr** [belzaru17/WorkshopOptimizerPlugin#13]
I tried to find an option to exclude craftables that I don't have the resources for, but it doesn't seem to exist.

**Comment by belzaru17** [comment]
You can go to the items tab and mark it as "Never".  It's not persisted, though.

**Comment by ChrisZehr** [comment]
I guess that's a decent workaround, but I'd still like to suggest adding an option.  Thanks for the speedy response.

**Comment by belzaru17** [comment]
Do you have in mind craftables you haven't unlocked yet, or just those that you don't have materials.

Never though of the latter since I usually plan & then gather whatever I have missing.

**Comment by ChrisZehr** [comment]
I mostly just mean crops and stable drops specifically, because if I set an
agenda that includes tomatoes or claws I can't just go gather more tomatoes
or claws, I have to wait 3 days to grow them or I might not have the animal
in my stable.

**Comment by belzaru17** [comment]
I'll have a look over the weekend.  Doing it properly (i.e.; taking into account the number of items you have left) is a bit expensive and requires a lot of changes, but just ignoring craftables you have 0 rare items should be straightforward - I think.

**Comment by ChrisZehr** [comment]
Cool, I appreciate the consideration! Aside from that, I still find this
addon very useful.

**Comment by belzaru17** [comment]
Looked at it today and have a half working solution.  I'll keep you updated.

**Comment by belzaru17** [comment]
Pull request sent - change will be included in 0.2.8.2.
