### ISSUE TITLE
Minor UX suggestion

### ISSUE THREAD

**Issue by retep998** [belzaru17/WorkshopOptimizerPlugin#15]
For these things where there is a thing to choose a value with a label next to it, could you please put the label to the left instead of to the right?
![image](https://github.com/belzaru17/WorkshopOptimizerPlugin/assets/666308/e9452a24-27fd-495e-96e3-f17f6ddc629a)
I keep thinking that the number indicating which cycle I want to optimize for is actually the season, and that the 10 has something to do with groove rather than how many options I want displayed.

**Comment by belzaru17** [comment]
Sorry, was away. Thanks for the suggestion, let me have a look.

**Comment by belzaru17** [comment]
0.2.8.3 includes the alignment change.  Pull request sent, so should be live once approved.
