### ISSUE TITLE
Corn Flake value's off

### ISSUE THREAD

**Issue by Blank-spacez** [belzaru17/WorkshopOptimizerPlugin#17]
![Corn Flakes](https://github.com/belzaru17/WorkshopOptimizerPlugin/assets/173460161/082c3731-3c10-4f3f-b3d4-3fbfbebc0f56)

Hi, love your mod! I have been using it for quite awhile since i started the workshop.
The base value of the corn flakes is off by a bit. Just an update of the value from 42 to 52 under ItemStaticData.cs should do the trick.

**Comment by belzaru17** [comment]
Thanks! Happy to hear you're finding it useful.

Good catch, fixed.  Pull Request for 0.2.8.4 sent for main repo and should be live after they approve it.

Thanks again!
