### ISSUE TITLE
How to install plugin?

### ISSUE THREAD

**Issue by moonk1sses** [belzaru17/WorkshopOptimizerPlugin#2]

**Comment by Nin9sKi** [comment]
I was also wondering about that. Can't seem to find it anywhere or find a repo..

**Comment by belzaru17** [comment]
Hi! 6.3 introduced some changes that I still need to sort out; once that's done I'll publish it properly.

**Comment by belzaru17** [comment]
Fixes for 6.3 should be working now.

Added repo (https://raw.githubusercontent.com/belzaru17/WorkshopOptimizerPlugin/main/repo.json) and install instrucitons.
