### ISSUE TITLE
Unable to install via Dalamud repo

### ISSUE THREAD

**Issue by lovelydumpling** [belzaru17/WorkshopOptimizerPlugin#4]
![image](https://user-images.githubusercontent.com/30986053/235410203-45bc79a8-07dc-474b-bb30-a60cbf8d2e88.png)

**Comment by belzaru17** [comment]
Thanks for the report. 

Do you have logs or something that helps track it down? I couldn't reproduce it myself.

**Comment by lovelydumpling** [comment]
Nevermind, it's just working now. I have no idea what caused it but I tried it multiple times last night to no avail. Now it's just working.
