### ISSUE TITLE
Isleworks Stove listed as 4 hours instead of 6 hours.

### ISSUE THREAD

**Issue by JellyBlade** [belzaru17/WorkshopOptimizerPlugin#5]
Just noticed this today when setting up my schedule for the rest of the week, WSO suggested a 4/8/4/8 pattern using Islework Stove as the 4-hour craft, which isn't possible.

I also took a quick glance at some of the other workshop items added recently, but this seems to be the only one with improper listed time.

![image](https://github.com/belzaru17/WorkshopOptimizerPlugin/assets/4555773/8fb1333b-3d99-42d4-a2dc-8f890c1e59c2)

**Comment by sldrazga** [comment]
Just here to comment that this also throws off patterns-- i.e. WSO suggests, for example: earrings/silver ear cuffs/stove/bed, but the combination isn't possible because the bed is 8 hours and thus would go over the 24hr day.

**Comment by belzaru17** [comment]
Apologies for the delay, I was on holidays.  Thanks for the fixes!
