### ISSUE TITLE
Natron is wrongly listed as Confections instead of Concoctions

### ISSUE THREAD

**Issue by Minizinger** [belzaru17/WorkshopOptimizerPlugin#6]
Probably a typo. This is breaking the calculations, causing combinations without bonus to be suggested

https://github.com/belzaru17/WorkshopOptimizerPlugin/blob/main/WorkshopOptimizerPlugin/Data/ItemStaticData.cs#L112

**Comment by belzaru17** [comment]
Apologies for the delay, I was on holidays.  Thanks for the fixes!
